// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodFlix;

#nullable disable

namespace MoodFlix.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125175933_AddedCountryCodeColumnInPlatform")]
    partial class AddedCountryCodeColumnInPlatform
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoodFlix.Model.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 0,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 1,
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "AntiguaAndBarbuda"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryName = "BosniaAndHerzegovina"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryName = "Brunei"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 26,
                            CountryName = "BurkinaFaso"
                        },
                        new
                        {
                            CountryId = 27,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryId = 28,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryId = 29,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryId = 30,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = 31,
                            CountryName = "CapeVerde"
                        },
                        new
                        {
                            CountryId = 32,
                            CountryName = "CentralAfricanRepublic"
                        },
                        new
                        {
                            CountryId = 33,
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryId = 34,
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = 35,
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = 36,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryId = 37,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryId = 38,
                            CountryName = "CongoDemocraticRepublic"
                        },
                        new
                        {
                            CountryId = 39,
                            CountryName = "CongoRepublic"
                        },
                        new
                        {
                            CountryId = 40,
                            CountryName = "CostaRica"
                        },
                        new
                        {
                            CountryId = 41,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryId = 42,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryId = 43,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryId = 44,
                            CountryName = "CzechRepublic"
                        },
                        new
                        {
                            CountryId = 45,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryId = 46,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryId = 47,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryId = 48,
                            CountryName = "DominicanRepublic"
                        },
                        new
                        {
                            CountryId = 49,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryId = 50,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryId = 51,
                            CountryName = "ElSalvador"
                        },
                        new
                        {
                            CountryId = 52,
                            CountryName = "EquatorialGuinea"
                        },
                        new
                        {
                            CountryId = 53,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryId = 54,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryId = 55,
                            CountryName = "Eswatini"
                        },
                        new
                        {
                            CountryId = 56,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 57,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryId = 58,
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryId = 59,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = 60,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryId = 61,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            CountryId = 62,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryId = 63,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = 64,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryId = 65,
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryId = 66,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryId = 67,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryId = 68,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryId = 69,
                            CountryName = "GuineaBissau"
                        },
                        new
                        {
                            CountryId = 70,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryId = 71,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryId = 72,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryId = 73,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryId = 74,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryId = 75,
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = 76,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = 77,
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = 78,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryId = 79,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryId = 80,
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryId = 81,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = 82,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryId = 83,
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = 84,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryId = 85,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 86,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryId = 87,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryId = 88,
                            CountryName = "KoreaNorth"
                        },
                        new
                        {
                            CountryId = 89,
                            CountryName = "KoreaSouth"
                        },
                        new
                        {
                            CountryId = 90,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = 91,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 92,
                            CountryName = "Laos"
                        },
                        new
                        {
                            CountryId = 93,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryId = 94,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryId = 95,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryId = 96,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryId = 97,
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryId = 98,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 99,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryId = 100,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 101,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryId = 102,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryId = 103,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryId = 104,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryId = 105,
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryId = 106,
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryId = 107,
                            CountryName = "MarshallIslands"
                        },
                        new
                        {
                            CountryId = 108,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryId = 109,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryId = 110,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryId = 111,
                            CountryName = "Micronesia"
                        },
                        new
                        {
                            CountryId = 112,
                            CountryName = "Moldova"
                        },
                        new
                        {
                            CountryId = 113,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryId = 114,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryId = 115,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryId = 116,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryId = 117,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryId = 118,
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryId = 119,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryId = 120,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryId = 121,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryId = 122,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryId = 123,
                            CountryName = "NewZealand"
                        },
                        new
                        {
                            CountryId = 124,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 125,
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryId = 126,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryId = 127,
                            CountryName = "NorthMacedonia"
                        },
                        new
                        {
                            CountryId = 128,
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = 129,
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = 130,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryId = 131,
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryId = 132,
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryId = 133,
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryId = 134,
                            CountryName = "PapuaNewGuinea"
                        },
                        new
                        {
                            CountryId = 135,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryId = 136,
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryId = 137,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = 138,
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryId = 139,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryId = 140,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = 141,
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryId = 142,
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryId = 143,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryId = 144,
                            CountryName = "SaintKittsAndNevis"
                        },
                        new
                        {
                            CountryId = 145,
                            CountryName = "SaintLucia"
                        },
                        new
                        {
                            CountryId = 146,
                            CountryName = "SaintVincentAndTheGrenadines"
                        },
                        new
                        {
                            CountryId = 147,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryId = 148,
                            CountryName = "SanMarino"
                        },
                        new
                        {
                            CountryId = 149,
                            CountryName = "SaoTomeAndPrincipe"
                        },
                        new
                        {
                            CountryId = 150,
                            CountryName = "SaudiArabia"
                        },
                        new
                        {
                            CountryId = 151,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryId = 152,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryId = 153,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryId = 154,
                            CountryName = "SierraLeone"
                        },
                        new
                        {
                            CountryId = 155,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryId = 156,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryId = 157,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryId = 158,
                            CountryName = "SolomonIslands"
                        },
                        new
                        {
                            CountryId = 159,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryId = 160,
                            CountryName = "SouthAfrica"
                        },
                        new
                        {
                            CountryId = 161,
                            CountryName = "SouthSudan"
                        },
                        new
                        {
                            CountryId = 162,
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryId = 163,
                            CountryName = "SriLanka"
                        },
                        new
                        {
                            CountryId = 164,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryId = 165,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            CountryId = 166,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = 167,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryId = 168,
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryId = 169,
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            CountryId = 170,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 171,
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            CountryId = 172,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = 173,
                            CountryName = "TimorLeste"
                        },
                        new
                        {
                            CountryId = 174,
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryId = 175,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryId = 176,
                            CountryName = "TrinidadAndTobago"
                        },
                        new
                        {
                            CountryId = 177,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryId = 178,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryId = 179,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 180,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 181,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryId = 182,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryId = 183,
                            CountryName = "UnitedArabEmirates"
                        },
                        new
                        {
                            CountryId = 184,
                            CountryName = "UnitedKingdom"
                        },
                        new
                        {
                            CountryId = 185,
                            CountryName = "UnitedStates"
                        },
                        new
                        {
                            CountryId = 186,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryId = 187,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 188,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 189,
                            CountryName = "VaticanCity"
                        },
                        new
                        {
                            CountryId = 190,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            CountryId = 191,
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            CountryId = 192,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryId = 193,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryId = 194,
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MoodFlix.Model.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectorId"));

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorId");

                    b.ToTable("Director");
                });

            modelBuilder.Entity("MoodFlix.Model.DirectorMovie", b =>
                {
                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("DirectorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("DirectorMovie");
                });

            modelBuilder.Entity("MoodFlix.Model.Emotion", b =>
                {
                    b.Property<int>("EmotionId")
                        .HasColumnType("int");

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmotionId");

                    b.ToTable("Emotion");

                    b.HasData(
                        new
                        {
                            EmotionId = 0,
                            EmotionName = "Boredom"
                        },
                        new
                        {
                            EmotionId = 1,
                            EmotionName = "Admiration"
                        },
                        new
                        {
                            EmotionId = 2,
                            EmotionName = "Adoration"
                        },
                        new
                        {
                            EmotionId = 3,
                            EmotionName = "Joy"
                        },
                        new
                        {
                            EmotionId = 4,
                            EmotionName = "Love"
                        },
                        new
                        {
                            EmotionId = 5,
                            EmotionName = "Craving"
                        },
                        new
                        {
                            EmotionId = 6,
                            EmotionName = "Anxiety"
                        },
                        new
                        {
                            EmotionId = 7,
                            EmotionName = "AestheticAppreciation"
                        },
                        new
                        {
                            EmotionId = 8,
                            EmotionName = "Amazement"
                        },
                        new
                        {
                            EmotionId = 9,
                            EmotionName = "Calmness"
                        },
                        new
                        {
                            EmotionId = 10,
                            EmotionName = "Confusion"
                        },
                        new
                        {
                            EmotionId = 11,
                            EmotionName = "Lust"
                        },
                        new
                        {
                            EmotionId = 12,
                            EmotionName = "Disgust"
                        },
                        new
                        {
                            EmotionId = 13,
                            EmotionName = "Fun"
                        },
                        new
                        {
                            EmotionId = 14,
                            EmotionName = "EmpathicPain"
                        },
                        new
                        {
                            EmotionId = 15,
                            EmotionName = "Anger"
                        },
                        new
                        {
                            EmotionId = 16,
                            EmotionName = "Envy"
                        },
                        new
                        {
                            EmotionId = 17,
                            EmotionName = "Ecstasy"
                        },
                        new
                        {
                            EmotionId = 18,
                            EmotionName = "Horror"
                        },
                        new
                        {
                            EmotionId = 19,
                            EmotionName = "Interest"
                        },
                        new
                        {
                            EmotionId = 20,
                            EmotionName = "Fear"
                        },
                        new
                        {
                            EmotionId = 21,
                            EmotionName = "Nostalgia"
                        },
                        new
                        {
                            EmotionId = 22,
                            EmotionName = "Satisfaction"
                        },
                        new
                        {
                            EmotionId = 23,
                            EmotionName = "Sympathy"
                        },
                        new
                        {
                            EmotionId = 24,
                            EmotionName = "Sadness"
                        },
                        new
                        {
                            EmotionId = 25,
                            EmotionName = "Triumph"
                        },
                        new
                        {
                            EmotionId = 26,
                            EmotionName = "Shame"
                        });
                });

            modelBuilder.Entity("MoodFlix.Model.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 0,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 1,
                            GenreName = "Adventure"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Animation"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Crime"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Documentary"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Drama"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Family"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "History"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 11,
                            GenreName = "Music"
                        },
                        new
                        {
                            GenreId = 12,
                            GenreName = "Mystery"
                        },
                        new
                        {
                            GenreId = 13,
                            GenreName = "News"
                        },
                        new
                        {
                            GenreId = 14,
                            GenreName = "Reality"
                        },
                        new
                        {
                            GenreId = 15,
                            GenreName = "Romance"
                        },
                        new
                        {
                            GenreId = 16,
                            GenreName = "ScienceFiction"
                        },
                        new
                        {
                            GenreId = 17,
                            GenreName = "TalkShow"
                        },
                        new
                        {
                            GenreId = 18,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            GenreId = 19,
                            GenreName = "War"
                        },
                        new
                        {
                            GenreId = 20,
                            GenreName = "Western"
                        });
                });

            modelBuilder.Entity("MoodFlix.Model.GenreMovie", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("MoodFlix.Model.HistoryEmotion", b =>
                {
                    b.Property<int>("HistoryEmotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryEmotionId"));

                    b.Property<int>("EmotionId")
                        .HasColumnType("int");

                    b.Property<int>("RegisterId")
                        .HasColumnType("int");

                    b.HasKey("HistoryEmotionId");

                    b.HasIndex("EmotionId");

                    b.HasIndex("RegisterId");

                    b.ToTable("HistoryEmotion");
                });

            modelBuilder.Entity("MoodFlix.Model.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("HorizontalPosterw360")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorizontalPosterw480")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorizontalPosterw720")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MoodFlix.Model.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("MoodFlix.Model.Register", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RegisterId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("MoodFlix.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MoodFlix.Model.UserGenre", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("UserGenre");
                });

            modelBuilder.Entity("MoodFlix.Model.UserPlatform", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("UserPlatform");
                });

            modelBuilder.Entity("MoodFlix.Model.DirectorMovie", b =>
                {
                    b.HasOne("MoodFlix.Model.Director", "Director")
                        .WithMany("DirectorMovies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodFlix.Model.Movie", "Movie")
                        .WithMany("DirectorMovie")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoodFlix.Model.GenreMovie", b =>
                {
                    b.HasOne("MoodFlix.Model.Genre", "Genre")
                        .WithMany("GenreMovies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodFlix.Model.Movie", "Movie")
                        .WithMany("GenreMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoodFlix.Model.HistoryEmotion", b =>
                {
                    b.HasOne("MoodFlix.Model.Emotion", "Emotion")
                        .WithMany("HistoryEmotions")
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodFlix.Model.Register", "Register")
                        .WithMany("HistoryEmotions")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emotion");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("MoodFlix.Model.Register", b =>
                {
                    b.HasOne("MoodFlix.Model.Movie", "Movie")
                        .WithMany("Registers")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodFlix.Model.User", "User")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodFlix.Model.User", b =>
                {
                    b.HasOne("MoodFlix.Model.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MoodFlix.Model.UserGenre", b =>
                {
                    b.HasOne("MoodFlix.Model.Genre", "Genre")
                        .WithMany("UserGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodFlix.Model.User", "User")
                        .WithMany("UserGenres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodFlix.Model.UserPlatform", b =>
                {
                    b.HasOne("MoodFlix.Model.Platform", "Platform")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodFlix.Model.User", "User")
                        .WithMany("UserPlatforms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodFlix.Model.Country", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MoodFlix.Model.Director", b =>
                {
                    b.Navigation("DirectorMovies");
                });

            modelBuilder.Entity("MoodFlix.Model.Emotion", b =>
                {
                    b.Navigation("HistoryEmotions");
                });

            modelBuilder.Entity("MoodFlix.Model.Genre", b =>
                {
                    b.Navigation("GenreMovies");

                    b.Navigation("UserGenres");
                });

            modelBuilder.Entity("MoodFlix.Model.Movie", b =>
                {
                    b.Navigation("DirectorMovie");

                    b.Navigation("GenreMovies");

                    b.Navigation("Registers");
                });

            modelBuilder.Entity("MoodFlix.Model.Platform", b =>
                {
                    b.Navigation("UserPlatforms");
                });

            modelBuilder.Entity("MoodFlix.Model.Register", b =>
                {
                    b.Navigation("HistoryEmotions");
                });

            modelBuilder.Entity("MoodFlix.Model.User", b =>
                {
                    b.Navigation("History");

                    b.Navigation("UserGenres");

                    b.Navigation("UserPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
