namespace MoodFlix.Model
{
    public enum EnumCountry
    {
        AF = 0, // Afghanistan
        AL = 1, // Albania
        DZ = 2, // Algeria
        AD = 3, // Andorra
        AO = 4, // Angola
        AG = 5, // Antigua and Barbuda
        AR = 6, // Argentina
        AM = 7, // Armenia
        AU = 8, // Australia
        AT = 9, // Austria
        AZ = 10, // Azerbaijan
        BS = 11, // Bahamas
        BH = 12, // Bahrain
        BD = 13, // Bangladesh
        BB = 14, // Barbados
        BY = 15, // Belarus
        BE = 16, // Belgium
        BZ = 17, // Belize
        BJ = 18, // Benin
        BT = 19, // Bhutan
        BO = 20, // Bolivia
        BA = 21, // Bosnia and Herzegovina
        BW = 22, // Botswana
        BR = 23, // Brazil
        BN = 24, // Brunei
        BG = 25, // Bulgaria
        BF = 26, // Burkina Faso
        BI = 27, // Burundi
        KH = 28, // Cambodia
        CM = 29, // Cameroon
        CA = 30, // Canada
        CV = 31, // Cape Verde
        CF = 32, // Central African Republic
        TD = 33, // Chad
        CL = 34, // Chile
        CN = 35, // China
        CO = 36, // Colombia
        KM = 37, // Comoros
        CD = 38, // Congo (Democratic Republic)
        CG = 39, // Congo (Republic)
        CR = 40, // Costa Rica
        HR = 41, // Croatia
        CU = 42, // Cuba
        CY = 43, // Cyprus
        CZ = 44, // Czech Republic
        DK = 45, // Denmark
        DJ = 46, // Djibouti
        DM = 47, // Dominica
        DO = 48, // Dominican Republic
        EC = 49, // Ecuador
        EG = 50, // Egypt
        SV = 51, // El Salvador
        GQ = 52, // Equatorial Guinea
        ER = 53, // Eritrea
        EE = 54, // Estonia
        SZ = 55, // Eswatini
        ET = 56, // Ethiopia
        FJ = 57, // Fiji
        FI = 58, // Finland
        FR = 59, // France
        GA = 60, // Gabon
        GM = 61, // Gambia
        GE = 62, // Georgia
        DE = 63, // Germany
        GH = 64, // Ghana
        GR = 65, // Greece
        GD = 66, // Grenada
        GT = 67, // Guatemala
        GN = 68, // Guinea
        GW = 69, // Guinea-Bissau
        GY = 70, // Guyana
        HT = 71, // Haiti
        HN = 72, // Honduras
        HU = 73, // Hungary
        IS = 74, // Iceland
        IN = 75, // India
        ID = 76, // Indonesia
        IR = 77, // Iran
        IQ = 78, // Iraq
        IE = 79, // Ireland
        IL = 80, // Israel
        IT = 81, // Italy
        JM = 82, // Jamaica
        JP = 83, // Japan
        JO = 84, // Jordan
        KZ = 85, // Kazakhstan
        KE = 86, // Kenya
        KI = 87, // Kiribati
        KP = 88, // Korea (North)
        KR = 89, // Korea (South)
        KW = 90, // Kuwait
        KG = 91, // Kyrgyzstan
        LA = 92, // Laos
        LV = 93, // Latvia
        LB = 94, // Lebanon
        LS = 95, // Lesotho
        LR = 96, // Liberia
        LY = 97, // Libya
        LI = 98, // Liechtenstein
        LT = 99, // Lithuania
        LU = 100, // Luxembourg
        MG = 101, // Madagascar
        MW = 102, // Malawi
        MY = 103, // Malaysia
        MV = 104, // Maldives
        ML = 105, // Mali
        MT = 106, // Malta
        MH = 107, // Marshall Islands
        MR = 108, // Mauritania
        MU = 109, // Mauritius
        MX = 110, // Mexico
        FM = 111, // Micronesia
        MD = 112, // Moldova
        MC = 113, // Monaco
        MN = 114, // Mongolia
        ME = 115, // Montenegro
        MA = 116, // Morocco
        MZ = 117, // Mozambique
        MM = 118, // Myanmar
        NA = 119, // Namibia
        NR = 120, // Nauru
        NP = 121, // Nepal
        NL = 122, // Netherlands
        NZ = 123, // New Zealand
        NI = 124, // Nicaragua
        NE = 125, // Niger
        NG = 126, // Nigeria
        MK = 127, // North Macedonia
        NO = 128, // Norway
        OM = 129, // Oman
        PK = 130, // Pakistan
        PW = 131, // Palau
        PS = 132, // Palestine
        PA = 133, // Panama
        PG = 134, // Papua New Guinea
        PY = 135, // Paraguay
        PE = 136, // Peru
        PH = 137, // Philippines
        PL = 138, // Poland
        PT = 139, // Portugal
        QA = 140, // Qatar
        RO = 141, // Romania
        RU = 142, // Russia
        RW = 143, // Rwanda
        KN = 144, // Saint Kitts and Nevis
        LC = 145, // Saint Lucia
        VC = 146, // Saint Vincent and the Grenadines
        WS = 147, // Samoa
        SM = 148, // San Marino
        ST = 149, // Sao Tome and Principe
        SA = 150, // Saudi Arabia
        SN = 151, // Senegal
        RS = 152, // Serbia
        SC = 153, // Seychelles
        SL = 154, // Sierra Leone
        SG = 155, // Singapore
        SK = 156, // Slovakia
        SI = 157, // Slovenia
        SB = 158, // Solomon Islands
        SO = 159, // Somalia
        ZA = 160, // South Africa
        SS = 161, // South Sudan
        ES = 162, // Spain
        LK = 163, // Sri Lanka
        SD = 164, // Sudan
        SR = 165, // Suriname
        SE = 166, // Sweden
        CH = 167, // Switzerland
        SY = 168, // Syria
        TW = 169, // Taiwan
        TJ = 170, // Tajikistan
        TZ = 171, // Tanzania
        TH = 172, // Thailand
        TL = 173, // Timor-Leste
        TG = 174, // Togo
        TO = 175, // Tonga
        TT = 176, // Trinidad and Tobago
        TN = 177, // Tunisia
        TR = 178, // Turkey
        TM = 179, // Turkmenistan
        TV = 180, // Tuvalu
        UG = 181, // Uganda
        UA = 182, // Ukraine
        AE = 183, // United Arab Emirates
        GB = 184, // United Kingdom
        US = 185, // United States
        UY = 186, // Uruguay
        UZ = 187, // Uzbekistan
        VU = 188, // Vanuatu
        VA = 189, // Vatican City
        VE = 190, // Venezuela
        VN = 191, // Vietnam
        YE = 192, // Yemen
        ZM = 193, // Zambia
        ZW = 194  // Zimbabwe
    }
}
